### PR TITLE
Update common.mk

### PR DESCRIPTION
**Pull request by beckermr**

### CODE REVIEW

**Comment by lgarrison** [comment]
Thanks!  Was `sysconfig.get_config_var(x)` coming up `None` for some variable?  Do you know which variable and Python environment?

**Comment by beckermr** [comment]
It as on pypy, not cpython.

**Comment by lgarrison** [comment]
Good to know, I haven't used PyPy myself, nor do we have any tests for it.

@manodeep Do we want to be really thorough and start doing PyPy tests?  Or figure that users will report problems if they find any...

**Comment by beckermr** [comment]
Yeah no need to worry about pypy. It is a corner case. I was trying a patch on the build but it is not working on osx. I am going to close this PR and just skip pypy.

**Pull request closed without merging**
