### PR TITLE
Update countspheres_mocks_impl.c.src

### PR DESCRIPTION
**Pull request by gbeltzmo**
Moving free(xran);free(yran);free(zran); from line 405 to line 538 to resolve seg fault.

### CODE REVIEW

**Comment by manodeep** [comment]
@lgarrison I don't understand why the astropy-bot is unhappy. Do you know?

**Comment by lgarrison** [comment]
Yeah, I think the changelog entry needs the PR number instead of the issue number (and possibly in brackets instead of parentheses?).

**Comment by manodeep** [comment]
@gbeltzmo Will you please try out what @lgarrison said and see if the astropy-bot is happy...

If not, we will just merge in the PR, and fix it at our end. Thanks again @gbeltzmo

**Comment by manodeep** [comment]
@gbeltzmo The PR # is "168", ie replace `(#150)` with `[#168]` in `Changes.rst`.

**Comment by manodeep** [comment]
Un-related bug from numpy dependency is failing the build. Merging this in

**Pull request merged**
