### PR TITLE
Code quality fixes

### PR DESCRIPTION
**Pull request by manodeep**

### CODE REVIEW

**Comment by manodeep** [comment]
@lgarrison Please feel free to add any other code quality fixes onto this PR.

**Comment by manodeep** [comment]
Before merging this PR, we need to add the bug fix for #192 into the `CHANGES.rst` file.

**Comment by manodeep** [comment]
@lgarrison When you have a chance, will you give the changes a look-over, particularly the duplicate ngb-cell check that I just added through e53bce3050139337dae5723a3601e707f1f37920.

**Comment by lgarrison** [comment]
Yes, I'll take a look in more detail soon!  But just skimming the diff, it
looks like we're doing a brute-force check for cell duplication.  Is it not
possible to simply construct the neighbor list without the duplicates to
begin with?

**Comment by manodeep** [comment]
You could almost certainly make the duplication check better. Because that check takes so little time and is likely to come up under very special circumstances, I opted for the brute-force check. Happy to have a brainstorm to see if we can improve the check.

**Comment by manodeep** [comment]
Agreed! We need to either add the threads within that `generate_cell_pairs` or incorporate the async model to generate and consume the cell-pairs

**Pull request merged**
