### PR TITLE
Updated GitHub CI

### PR DESCRIPTION
**Pull request by manodeep**
Upgraded min python and numpy versions, and changed the compiler versions and the linux os's tested

### CODE REVIEW

**Comment by manodeep** [comment]
Need to add Changelog. Not sure why the astropy bot is not running

**Review by lgarrison — APPROVED** [review]
Looks good, thanks for taking the time to update this!

Minor question: what's the motivation behind testing both the 1.22 and 1.23 versions of Numpy? Was there a C API change?

**Comment by manodeep** [comment]
Thanks @lgarrison. Nothing in particular, figured it would be better to test out the recent python and numpy versions - that's where I would expect things to break, if at all.

**Comment by manodeep** [comment]
@lgarrison Do we not have the astropy milestones checker bot anymore?

**Comment by lgarrison** [comment]
I guess not. It looks like astropy has migrated to GH actions instead. E.g. for changelog checking: https://github.com/astropy/astropy/blob/main/.github/workflows/check_changelog.yml, with the bot living at https://github.com/pllim/actions-towncrier-changelog

**Comment by manodeep** [comment]
Fixed the conflict in the changelog. 

Looks like we would need to migrate to pyproject.toml before we can use towncrier and allied actions. That's beyond my knowledge - do you know how to do that?

**Comment by manodeep** [comment]
@lgarrison Okay to merge?

**Comment by lgarrison** [comment]
Yep, LGTM!

For `pyproject.toml`, in theory it's not too hard to set up while still keeping most of the work in `setup.py`, but the Corrfunc build has enough quirks/customizations that it would need some careful testing before we deploy anything.  But towncrier might not actually need a fully-fledged `toml` file; maybe it just needs the sections relevant to it?

**Pull request merged**
