### PR TITLE
Removed independent volume check in vpf.py

### PR DESCRIPTION
**Pull request by laperezNYC**
Following the discussion in issue #237 and after conversations with LGarrison, I've completely removed the check that confirmed that the volume inhabited by the dropped spheres was less than the volume of the sample. This check was unnecessary for the VPF to run, and actively discouraged the oversampling of the sample volume with test spheres that one needs to precisely measure the VPF at a given radius.

### CODE REVIEW

**Comment by lgarrison** [comment]
Thanks! The CI failures are not your fault, they're on the backend.  I've updated master with the fix, can you re-merge master into your branch?  You may have to add this repo as an upstream remote, if it's not there already:
```
git remote add upstream https://github.com/manodeep/Corrfunc.git
git fetch upstream
git merge upstream/master
git push
```
or something close to that!

Also, the volume calculation above your edits can probably be removed too.

**Comment by manodeep** [comment]
@laperezNYC Thanks for the PR! Will you please add an entry to the `CHANGES.rst` file under the version entry for `2.4.0`[here](https://github.com/manodeep/Corrfunc/blob/master/CHANGES.rst#240-upcoming)?

@lgarrison Did the astropy bot run the usual checks on this PR? Not seeing it...

**Comment by lgarrison** [comment]
Yeah, I was wondering about the bot too.  Don't see it...

**Comment by manodeep** [comment]
Saw that the bot was requesting some additional permissions (read + write to checks, read + write to members) - granted those permissions. Hopefully, that causes the bot to run at the next commit + update

**Review by lgarrison — APPROVED** [review]

**Comment by manodeep** [comment]
@laperezNYC Had not realised that this PR was still outstanding! Thanks for the contribution

**Pull request merged**
