### PR TITLE
benchmarks on CI

### PR DESCRIPTION
**Pull request by manodeep**
Trying to setup the benchmarks in the CI. We will need actual python code to run the benchmarks.

We might have to merge this PR into master before we can see whether the benchmarks are doing anything

### CODE REVIEW

**Comment by lgarrison** [comment]
Looks like the benchmark actions are running but failing. Can they be fixed in this PR before merging?

**Comment by manodeep** [comment]
Sorry - should have waited to click that "Review" button :D 

Many more things need to be added before this PR is ready for a review.

**Comment by manodeep** [comment]
Here is a nice CI workflow that summarises the benchmark through a comment on the open PR: [sympy/benchmark-summariser](https://github.com/sympy/sympy/actions/runs/4997707736/workflow)

Example comment in use [sympy-pr-#23746](https://github.com/sympy/sympy/pull/23746#issuecomment-1220058707)

**Comment by manodeep** [comment]
Will restart this PR once I have finished it

**Pull request closed without merging**
