### PR TITLE
Added a gsl version [ci skip]

### PR DESCRIPTION
**Pull request by manodeep**
In response to issue #163

### CODE REVIEW

**Comment by manodeep** [comment]
@lgarrison Will you please take a look? Seems simple enough to be able to merge straight into master. 

Not sure why the CI build failed -- restarted the tests

**Comment by manodeep** [comment]
Meant to request a review... :)

**Comment by lgarrison** [comment]
Do we need to add `conda install libgfortran` to the Python 2.6 test?  E.g. https://github.com/ContinuumIO/anaconda-issues/issues/445

I don't think it's critical we solve this in the most robust way possible, since we're deprecating the Python 2.6 version in the next release anyway.

**Comment by manodeep** [comment]
@lgarrison Did you figure out how to resolve the astropy bot's comment?

**Comment by lgarrison** [comment]
Yes: rename `CHANGELOG.rst` to `CHANGES.rst`.  It's implemented in #158, but I think we want to backport here as well.

**Comment by manodeep** [comment]
Oh my god - this bot is insistent. Hopefully, this is just initial pains; and comes with long-term gains in code quality. 

Thanks so much @lgarrison for handling this changelog fixing

**Comment by manodeep** [comment]
I think technically the `v2.1` release should really be called the `v2.1.0`

**Comment by lgarrison** [comment]
Okay, should we change the milestone?  I think that's the only way to make the bot happy.

**Comment by lgarrison** [comment]
Also just noting that one needs 6 equal signs to delineate a section; see https://github.com/astropy/astropy-bot/blob/master/changebot/blueprints/changelog_helpers.py#L31.

**Comment by manodeep** [comment]
Yup - I agree about changing the milestone. Let me do that; do you mind reverting back to the previous changelog entry

**Comment by manodeep** [comment]
Good to squash merge?

**Comment by lgarrison** [comment]
Yeah.  Technically Travis didn't check this, but everything after this build was changelog updates: https://travis-ci.org/manodeep/Corrfunc/builds/413307872

**Pull request merged**
