### PR TITLE
Allow python-config for Python 2 and Python 3

### LINKED ISSUE #156: Potential issue working with virtualenv
We have a user reporting unable to install nbodykit with pip, crashing at Corrfunc with virtualenv. 
```
    make[1]: Entering directory `/tmp/pip-install-hzbzub__/Corrfunc/theory'
    ../common.mk:372: "PYTHON" is set to /home/dc-pede1/virtualenv_directory/bin/python3.6; using /home/dc-pede1/virtualenv_directory/bin/python3-config as python-config. If this is not correct, please also set "PYTHON_CONFIG_EXE" in "common.mk" to appropriate python-config
    ../common.mk:377: *** python-config (/home/dc-pede1/virtualenv_directory/bin/python3-config) not found. Please set PYTHON_CONFIG_EXE in "common.mk" to appropriate python-config before installing Corrfunc.2.0.0 .  Stop.
    make[1]: Leaving directory `/tmp/pip-install-hzbzub__/Corrfunc/theory'
    make: *** [libs] Error 2
```
Some brief search lead me to this:

https://github.com/posborne/dbus-python/pull/1

Might be relevant? Perhaps the default make file shall try try a few additional paths. I don't know enough of virtualenv to say exactly what can be the best approach here. cc @Chris-Pedersen ?

### PR DESCRIPTION
**Pull request by lgarrison**
Fixes virtualenv install, which only links python-config instead of python3-config (closes #156)

I was able to reproduce the installation problem reported in #156 and confirm that this fixes it.

### CODE REVIEW

**Comment by lgarrison** [comment]
This works on Travis for all but Python 2.6, which doesn't have the `sysconfig` module, so `sysconfig.get_path('scripts')` fails.  `distutils.sysconfig` provides similar functionality on Python 2.6, but the canonical way to get the `bin/` dir via `distutils.sysconfig.get_config_var('BINDIR')` does not give the correct answer inside a virtualenv (points to the original location).

So we could use the hacky `distutils.sysconfig.EXEC_PREFIX + '/bin'`, or just drop Python 2.6 support...

**Comment by manodeep** [comment]
Thanks for sorting this out. I think we should completely remove the `python-config` dependence; all the flags we need are stored under `sysconfig`

One reason why I am proposing such a change is that I just looked at my python situation on my laptop and looks like `/usr/bin/python-config` is being picked up, even though I am using the python from `anaconda3/bin`. I also know of people that use `python` as an alias...

Separately, I think it is fine to drop `python2.6` support but we should make plans for future releases and document them, perhaps on the wiki. Such a drop for `python2.6` should probably be done in a minor version update `2.2` (with as-yet un-released `2.1` for `DDsmu*`)

**Comment by lgarrison** [comment]
What path do you get if you run `python -c "import sysconfig; print(sysconfig.get_path('scripts'));"`?  That's the solution that's implemented in this PR; the global `python-config` is never called.

**Comment by manodeep** [comment]
I get `/Users/msinha/anaconda3/bin` and there are a bunch of `python*-config` executables within there.

I would still say, when `python3` is being used, we check for `python3-config` first before checking `python-config`

**Comment by lgarrison** [comment]
Makes sense, although hopefully it won't make a difference either way.  I've pushed that and it seems to have passed Travis.

I also went ahead and dropped Python 2.6 support and edited the docs to reflect this.

**Comment by lgarrison** [comment]
Probably!  I figured we'd work out release versioning over Skype.

**Comment by manodeep** [comment]
New Corrfunc `2.1.0` is now live on PyPI

**Comment by manodeep** [comment]
@lgarrison Is it okay to delete the `venv_fix` branch now?

**Comment by lgarrison** [comment]
I think so? Unless we wanted to ask the original issue poster to verify the
fix out of master.

**Comment by manodeep** [comment]
I think the resolution was suggested by @rainwoodman - so should be okay. Deleting the branch; we can always un-delete if required. 

Related, should we add a `python_requires` into the `setup.py` file?

**Comment by lgarrison** [comment]
Yes, I think so.  I'll do that in my capture_stderr branch so we can CI it in one go.

**Pull request merged**
