### PR TITLE
Adding GitHub Actions for additional tests

### PR DESCRIPTION
**Pull request by manodeep**

### CODE REVIEW

**Comment by manodeep** [comment]
@lgarrison I added the tests with GitHub actions. However, I could not get clang working on linux, or gcc working on osx - so I had to disable those tests. Plus, I fixed some warnings that were being raised about uninitialised values and a minor cpython bug that was resulting in an improper function pointer cast.

Please let me know if you are okay with merging these in, or if you have ideas on how to fix the clang-on-linux/gcc-on-osx builds. (We can go up to 256 jobs in the matrix)

**Comment by lgarrison** [comment]
Cool, thanks!  Do you think we need both Ubuntu versions?  Just trying to think of ways to reduce the number of tests, I think too many can be cluttered and harder to maintain.

I think having an old and new Numpy version makes sense, but do you think we should test 1.18 (the latest) instead of 1.16?

Should we add a Python 3.8 test?  Or maybe we should deprecate Python 2.7 support first.  We're 6 months past end-of-life!

**Comment by manodeep** [comment]
The plan for dropping py2.7 was towards the end of 2020, if I recall correctly. What I would like to do is add in a DeprecationWarning, and then remove support in a later v2.x release. 

We can reduce the number of combinations that are tested, but I think we should test of a few different platforms. For instance, perhaps we should add in 16.04 but only test with gcc-7, py3.5, and numpy1.14. but then reduce the number of tests with 18.04 (may be remove a later gcc-version) and 20.04 (may be remove an earlier gcc-version).

I had py3.8 in the matrix too but had to drop it for (forget-what) some reason. Should I put py3.8 back in but only test in *one* config - say for a test config with ubuntu20.04, gcc-9, py3.8, numpy1.18? That would cover the latest gcc, python and numpy

**Comment by lgarrison** [comment]
Thanks, I think that sounds like a reasonable was to go with the Ubuntu versions and Python 3.8.

**Comment by manodeep** [comment]
Noting examples of GitHub Actions yml files that we might need to consult in the future - 

1. [CI in `doctest` for a range of os-compiler options](https://github.com/onqtam/doctest/blob/master/.github/workflows/main.yml)
2. [CI in `eigen-qld` for adding clang-formatting checks](https://github.com/jrl-umi3218/eigen-qld/blob/master/.github/workflows/build.yml)

**Comment by manodeep** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- setup.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/manodeep/Corrfunc/pullRequest?prid=5664078&bid=18539814)

**Comment by manodeep** [comment]
@lgarrison Will you please take a look again? I am done with the updates...

I tried to add in a separate CI for `INTEGRATION_TESTS` but those (unsurprisingly) timing out. So we will need a different solution (for instance, run each pair-counter as a separate stage), abandoning for now...

**Comment by lgarrison** [comment]
Looks good!  So does this supersede Travis, or is the plan to use both?

**Comment by manodeep** [comment]
We should just use both - no harm in extra checks

**Pull request merged**
