### PR TITLE
AVX512F kernels, min separation optimizations, not duplicating particle positions, array of cell-pairs

### PR DESCRIPTION
**Pull request by manodeep**
Also contains the `AVX512F` kernels. 

Needs to be verified by `valgrind` before merging.

### CODE REVIEW

**Comment by lgarrison** [comment]
Travis is passing tests, but integration tests reveal that the min-sep optimizations are dropping a particle when linking in RA.

**Comment by manodeep** [comment]
@lgarrison I added in the option for not duplicating the particle positions, **and** for creating a giant array of cell-pairs for the theory pair-counters. Tests passed on my laptop, not valgrind-ed properly, or checked with `INTEGRATION_TESTS`

**Comment by lgarrison** [comment]
Cool, thanks!  I think we should consider how we want to deal with copying the weights, too.  In any situation where it's acceptable to reorder the particle positions, it's probably acceptable to reorder the weights too.  So instead of `copy_particle_positions`, maybe it should just be called `copy_particles` (since it could be a position copy or a position and weights copy), or even just `inplace`.

**Comment by manodeep** [comment]
@lgarrison I was toying with having `inplace` but then I was having trouble naming the `reorder` option. I am totally fine with `copy_particles` (or `duplicate_particles`...)

**Comment by lgarrison** [comment]
If adding two parameters is annoying, we could do `inplace='allow_reorder'` (reorder and don't restore) `inplace='keep_order'` (reorder but restore), and `inplace=False` (make a copy).

We could also alias `True` to one of the reorder options, but I'm not sure which one we think would be more common/useful.

This may not be better than having two parameters, but it might be slightly less verbose...

**Comment by manodeep** [comment]
As you suggested, I renamed the `copy_particle_positions` to `copy_particles`. I think we want to keep the `reorder` separate, since someone might be re-using the same dataset.  By default, we should always shuffle back to the input order. 

Unfortunately, if someone selects `reorder=False`, then the input array for the next iteration is fully sorted, and that means the `quicksort` within `gridlink` will become `O(N^2)`. Ideally, we would have an `sglib` like implementation of `timsort` but I have not yet encountered any such open-source implentation

**Comment by manodeep** [comment]
@lgarrison I removed the `reorder` option entirely. That was causing too much of a conceptual load, plus the possibility of incorrect use. As it stands, if the `inplace` option has been used, everything will get reordered at the end. 

Since the "INTEGRATION_TESTS" get terminated by the OS (both OSX and linux) before running to completion, there is almost certainly some issue (possibly memory leak or out of bounds access) that's remains. I am going to investigate a bit further. 

In the mean-time, if you could do a code-review of this PR, that would be fantastic. Particularly, from the prospect of causing memory-leaks (from `copy_particles`) and from usability (should `copy_particles` be renamed to `inplace`, with the defaults changed appropriately)

**Comment by lgarrison** [comment]
Sure!  I'm handing in my thesis next week; should get to it right after
that.

**Comment by manodeep** [comment]
@pep8speaks suggest diff

**Comment by manodeep** [comment]
@lgarrison (Some?) Memory leaks are now fixed. Running integration tests with the `-fsanitize` options enabled - hopefully anything else will come up. Added these sanitize options to `gcc7.3.0` `-fsanitize=leak -fsanitize=undefined -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-undefined-trap-on-error -fstack-protector-all` - works great. And much much faster than valgrind.

**Comment by manodeep** [comment]
@pep8speaks pep8ify

**Comment by lgarrison** [comment]
@manodeep Can I bump the Travis Numpy version to 1.16 to fix the doctest failure?  I think it's a print formatting issue related to this: https://github.com/numpy/numpy/blob/master/doc/release/1.14.0-notes.rst#many-changes-to-array-printing-disableable-with-the-new-legacy-printing-mode

I changed the doctest output to match what I get on my local machine, hence the Travis failure.

Also, any idea why the astropy-bot is unhappy about the changelog?  The PR number is in there...

**Comment by manodeep** [comment]
@lgarrison numpy 1.16 is quite the latest - our numpy dependency is really quite minimal and, if we can, we should be fine with a reasonable version of numpy. I think the current requirement is `numpy >= 1.7`. Is this simply a white-space issue? Could we change the `print_options`?

For the astropy-bot failing the test, I am not really sure. May be it's because multiple issues are being addressed in the same PR? @bsipocz, if you have a spare moment, will you please take a look?

**Comment by lgarrison** [comment]
The current Travis Numpy version is already different from the minimum Corrfunc requirement.  We're at 1.12 on Travis but only require 1.7 for Corrfunc.  If we want to maintain backwards compatibility for the doctests I'm okay with that, but it does make the examples a fair bit more verbose (cluttered with Numpy print settings).  So I'd lean towards just bumping the Travis version past 1.13.

**Comment by manodeep** [comment]
@lgarrison It's a good point about the travis numpy testing that we are doing. And in some sense, Corrfunc is more likely to break if numpy drops backward compatibility or something. How many tests are affected by this whitespace printing issue? Basically, how much less fluffy code would be required if we bump the travis tests to numpy 1.16? Another option would be to disable doctests with the older version of numpy...

Thanks again for reading through - this PR definitely far too big! I am only mildly confident about nothing too crafty of a bug hiding in this PR because of the `-fsanitize`+ options with `INTEGRATION_TESTS` passing.

**Comment by bsipocz** [comment]
@manodeep - Not sure about the bot. It may be just that something went wrong with the trigger. You could try to retrigger, e.g. add/remove a label or milestone, etc.

**Comment by bsipocz** [comment]
Also, on the longer term I would suggest to change the travis settings as now it's triggered both as a pr and as a push. I basically just needs a couple of lines of extra logic in the config file. If you open a reminder issue and assign it to me I'll try to get back to it once I'm back in the US from travelling.

**Comment by lgarrison** [comment]
@manodeep I think it's only one test right now, so not too bad if we want to roll the backwards-compatible solution.  I'll push that and see how it works.

@bsipocz Thanks for the tip on eliminating the extra Travis build!  I've edited the config file to only build PRs and the master branch (following https://stackoverflow.com/a/31882307).  So commits on ordinary branches will not get built; we'll have to open a PR to trigger that.  But that may be closer to what we want anyway; when a feature or fix is ready for CI, it's probably mature enough for a PR.

The bot still remains stubborn even after editing the milestones/labels.

**Comment by manodeep** [comment]
@pllim said that the astropy-changelog bot could be getting tricked because of the multiple entries to the same PR. The full logic is [here](https://github.com/astropy/astropy-bot/blob/master/astropy_bot/changelog_checker.py)

Which means we would have to merge the descriptions of the new features into one change (at least what I understood was that reference to one specific PR is one entry in the changes)

**Comment by manodeep** [comment]
Sadly, my update to the changelog did not fix the bot issue

**Comment by manodeep** [comment]
@lgarrison If we can't figure out the changelog issue, may be we can skip formally having that check for this v2.3 release. Clearly there are entries in the changelog showing what has been done. What do you think?

**Comment by lgarrison** [comment]
Success!  I used [astropy-changelog](https://github.com/astropy/astropy-changelog) to directly parse our changelog, and it spit out a few warnings that I tracked down to a few small formatting issues:
- Having a literal block span multiple lines
- No indent on multi-line list item
- No newlines before starting nested list level
- Could not parse versions due to missing dates

I think the last item may have been the killer.

The RST parser wouldn't spit out line numbers for the warnings, which made it much harder to interpret.  If anyone knows how to enable this, it could be helpful for the future!

**Comment by lgarrison** [comment]
@manodeep Travis has passed on the last non-changelog commit, so I think we're ready to merge!

https://travis-ci.org/manodeep/Corrfunc/builds/535043527

**Comment by lgarrison** [comment]
Just noting that this PR has passed the integration tests on my AVX-512 machine (with gcc's AddressSanitizer).

**Pull request merged**
